In [1]:
import pandas as pd
import snscrape.modules.twitter as sntwitter
import itertools

In [2]:
num_of_tweets = 10
text_contained = "kilimo"
location = "dar es salaam"

In [3]:

data = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(text_contained+" "+'near:'+location).get_items(), 10))

In [4]:
data.head()

,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,https://twitter.com/mbezitznews/status/1615992...,2023-01-19 08:39:21+00:00,Majanga mikopo ya ujasiriamali\n\nSababu za Dk...,Majanga mikopo ya ujasiriamali\n\nSababu za Dk...,1615992294620160003,"{'username': 'mbezitznews', 'id': 868520013937...",0,0,0,0,...,NaN,None,None,None,None,None,None,None,55.0,None
1,https://twitter.com/darusoudsm/status/16131884...,2023-01-11 14:58:00+00:00,Uzinduzi wa Asasi ya kilimo Biashara na Uchumi...,Uzinduzi wa Asasi ya kilimo Biashara na Uchumi...,1613188482834243585,"{'username': 'darusoudsm', 'id': 1032193474500...",0,4,13,0,...,NaN,None,None,"{'longitude': 39.0081106, 'latitude': -7.1906489}","{'id': '00d9827647c0ff5a', 'fullName': 'Dar es...",None,None,None,340.0,None
2,https://twitter.com/Nipashetz/status/161290378...,2023-01-10 20:06:42+00:00,#HABARI Chuo kikuu cha Dar es Salaam kimezindu...,#HABARI Chuo kikuu cha Dar es Salaam kimezindu...,1612903782500679680,"{'username': 'Nipashetz', 'id': 3194223616, 'd...",0,2,12,0,...,NaN,None,None,None,None,[HABARI],None,None,833.0,None
3,https://twitter.com/spencer_minja/status/16128...,2023-01-10 17:52:50+00:00,Leo tumefanya uzinduzi wa “Dar es Salaam Unive...,Leo tumefanya uzinduzi wa “Dar es Salaam Unive...,1612870092391333888,"{'username': 'spencer_minja', 'id': 2729529304...",8,12,100,1,...,NaN,None,None,"{'longitude': 39.207448580663076, 'latitude': ...","{'id': '07d9cf662f887001', 'fullName': 'Univer...",None,None,None,6852.0,None
4,https://twitter.com/Mr_LazaroCO/status/1612760...,2023-01-10 10:37:39+00:00,Today I attend Duane launching events at Unive...,Today I attend Duane launching events at Unive...,1612760573577662464,"{'username': 'Mr_LazaroCO', 'id': 153304041037...",0,3,13,0,...,NaN,None,None,"{'longitude': 39.2041337578101, 'latitude': -6...","{'id': '07d9e74f29082001', 'fullName': 'UDSM M...",[kilimo],None,None,817.0,None